### ISSUE TITLE
Use of undeclared identifier 'SystemSettingsPlugin'  on iOS Simulators.

### ISSUE THREAD

**Issue by zinwalin** [fweinaug/system_settings#1]
![image](https://user-images.githubusercontent.com/5416196/83517231-18f2a580-a50b-11ea-8ee5-2cf367559651.png)

**Comment by fweinaug** [comment]
I just tested the example and it was working fine with the latest Flutter stable version (1.17.3).

Can you please provide more information on your setup, like which Flutter version are you using? Did you try Flutter clean?
