### ISSUE TITLE
Looks like this plugin is not working on iOS

### ISSUE THREAD

**Issue by cchamm** [fweinaug/system_settings#14]
I tried to run the example in simulator, but looks like it only redirect to Settings page. 

Device: iPhone 12 Pro (iOS 14.5) Simulator.

**Comment by Ilyes-Yhy** [comment]
I'm facing the same issue on a real IOS device [iPhone 11 with IOS 14.7.1]

**Comment by fweinaug** [comment]
unfortunately there is no better solution as mentioned in the snippet from the readme that @Ilyes-Yhy posted

**Comment by shahmirzali49** [comment]
@fweinaug how can we define SettingsBundle ?
