### ISSUE TITLE
What about null-safety?

### ISSUE THREAD

**Issue by darkstarx** [fweinaug/system_settings#7]
Does this lib support null-safety? Nothing in Readme.

**Comment by fweinaug** [comment]
I just released version 2.0 which is ready for null-safety. Please let me know if everything works out for you.

**Comment by darkstarx** [comment]
Great! Thanks a lot. Unfortunately I downgraded my flutter because some other libs used in my new project don't support Flutter 2 yet. So I'll check it as soon as I can.
