### ISSUE TITLE
Add API to open power/battery saving settings page

### ISSUE THREAD

**Issue by avkonst** [fweinaug/system_settings#9]
Hi,

Great set of APIs available already. Covers almost all my needs. Battery saving setting page would be great addition.

Thanks!

**Comment by fweinaug** [comment]
thanks for creating the issue! I just released version 2.1 which contains this feature thanks to @adarshnagrikar14

**Comment by adarshnagrikar14** [comment]
> thanks for creating the issue! I just released version 2.1 which contains this feature thanks to @adarshnagrikar14

Your welcome !
